import 'dart:convert';

/// Helpers for the order universal link
/// `https://thegreenmall.net/order?store_id=<id>&order_id=<id>`.
///
/// The customer's order QR now carries that URL instead of a bare JSON blob.
/// A URL is what makes the code camera-safe: a phone's native camera opens the
/// link (the installed app via Universal Link / App Link, or the website's
/// order page for people without the app) instead of treating a non-URL string
/// as a Google search — the exact failure reported in T2-452. The in-app store
/// scanner reads the same URL by pulling `store_id` / `order_id` off the query.
///
/// Legacy JSON payloads (`{"type":"order","order_id":..,"store_id":..}`) from
/// codes generated by older builds are still parsed, so a customer on an old
/// app and a store on a new one keep working.
class OrderLink {
  OrderLink._();

  static const String _base = 'https://thegreenmall.net';

  /// Hosts we accept an `/order` link from.
  static const Set<String> _hosts = {'thegreenmall.net', 'www.thegreenmall.net'};

  /// Build the universal-link QR payload for an order. [storeId] / [orderId]
  /// may be `int` or `String`; both stringify cleanly into the query.
  static String build({required Object storeId, required Object orderId}) =>
      '$_base/order?store_id=$storeId&order_id=$orderId';

  /// True when [raw] is an order universal link (host + `/order` path). Used by
  /// the deep-link router to tell order links apart from payment links.
  static bool isOrderLink(String raw) {
    final uri = Uri.tryParse(raw.trim());
    if (uri == null) return false;
    if (uri.scheme != 'https' && uri.scheme != 'http') return false;
    if (!_hosts.contains(uri.host.toLowerCase())) return false;
    final segments = uri.pathSegments.where((s) => s.isNotEmpty).toList();
    return segments.isNotEmpty && segments.first.toLowerCase() == 'order';
  }

  /// Parse a scanned/opened value into `{'storeId':.., 'orderId':..}`, accepting
  /// both the universal-link form and the legacy JSON payload. Returns null when
  /// [raw] is neither, or is missing either id.
  static Map<String, String>? parse(String raw) {
    final value = raw.trim();

    // Universal-link form:
    // https://thegreenmall.net/order?store_id=..&order_id=..
    if (isOrderLink(value)) {
      final uri = Uri.parse(value);
      final storeId = uri.queryParameters['store_id'] ?? '';
      final orderId = uri.queryParameters['order_id'] ?? '';
      if (storeId.isEmpty || orderId.isEmpty) return null;
      return {'storeId': storeId, 'orderId': orderId};
    }

    // Legacy JSON form: {"type":"order","order_id":..,"store_id":..}
    try {
      final decoded = jsonDecode(value);
      if (decoded is! Map || decoded['type'] != 'order') return null;
      final storeId = decoded['store_id']?.toString() ?? '';
      final orderId = decoded['order_id']?.toString() ?? '';
      if (storeId.isEmpty || orderId.isEmpty) return null;
      return {'storeId': storeId, 'orderId': orderId};
    } catch (_) {
      return null;
    }
  }
}
